#cloud-config

hostname: %XSVMNAMETOHOSTNAME%
ssh_authorized_keys:
  # The following entry will automatically be replaced with a public key
  # generated by XenServer's container management. The key-entry must exist,
  # in order to enable container management for this VM.
  - ssh-rsa %XSCONTAINERRSAPUB%
users:
   - name: core
     passwd: $1$17tYvTBd$RrkLVIogkO6D.C7HEhSAV.
     groups:
       - sudo
       - docker
coreos:
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

    # XenServer Linux Guest Agent
    - name: xe-linux-distribution.service
      command: start
      content: |
        [Unit]
        Description=XenServer Linux Guest Agent
        After=docker.service

        [Service]
        ExecStartPre=/media/configdrive/agent/xe-linux-distribution /var/cache/xe-linux-distribution
        Environment="XE_UPDATE_GUEST_ATTRS=/media/configdrive/agent/xe-update-guest-attrs"
        ExecStart=/media/configdrive/agent/xe-daemon
  etcd:
    name: %XSVMNAMETOHOSTNAME%
    # generate a new token for each unique cluster at https://discovery.etcd.io/new
    discovery: @@discovery_url@@
write_files:
    - path: /etc/systemd/network/static.network
      owner: core:core
      permissions: 0644
      content: |
        [Match]
        Name=eth0

        [Network]
        Address=@@ip@@/23
        Gateway=@@gw@@
        DNS=@@ns@@
    - path: /etc/systemd/system/docker.service.d/http-proxy.conf
      owner: core:core
      permissions: 0644
      content: |
        [Service]
        Environment="HTTP_PROXY=http://bremen.se.dfs.de:80" "NO_PROXY=localhost,127.0.0.0/8,10.232.0.0/23,se.dfs.de"
    - path: /etc/systemd/system/update-engine.service.d/proxy.conf
      permissions: 0644
      content: |
        [Service]
        Environment="ALL_PROXY=http://bremen:80" "HTTP_PROXY=http://bremen.se.dfs.de:80"
    - path: /etc/systemd/system/docker.service.d/insecure-registry.conf
      permissions: 0644
      content: |
        [Service]
        Environment=DOCKER_OPTS='--insecure-registry="dreg01.se.dfs.de:5000"'


  # Enable ARP notifications for smooth network recovery after migrations
  - path: /etc/sysctl.d/10-enable-arp-notify.conf
    permissions: 0644
    owner: root
    content: |
      net.ipv4.conf.all.arp_notify = 1


# Template loaded from /usr/lib/python2.4/site-packages/xscontainer/data/cloud-config.template
